SCALE Job started on Wed 13/02/2019 18:31:52
With Host name DESKTOP-J14NAA6
working directory C:\Users\Teddy\AppData\Local\Temp\scale.Teddy.12108
and process id 12108.
Input file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_57979.797980.inp
and output file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_57979.797980.out
##########################################################
***Warning:  The flux over a step has changed by more than 20%.
