SCALE Job started on Wed 13/02/2019 18:30:44
With Host name DESKTOP-J14NAA6
working directory C:\Users\Teddy\AppData\Local\Temp\scale.Teddy.10264
and process id 10264.
Input file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_46666.666667.inp
and output file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_46666.666667.out
##########################################################
***Warning:  The flux over a step has changed by more than 20%.
