SCALE Job started on Wed 13/02/2019 18:28:55
With Host name DESKTOP-J14NAA6
working directory C:\Users\Teddy\AppData\Local\Temp\scale.Teddy.10492
and process id 10492.
Input file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_26868.686869.inp
and output file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_26868.686869.out
##########################################################
