SCALE Job started on Wed 13/02/2019 18:27:45
With Host name DESKTOP-J14NAA6
working directory C:\Users\Teddy\AppData\Local\Temp\scale.Teddy.11804
and process id 11804.
Input file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_12020.202020.inp
and output file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_12020.202020.out
##########################################################
