SCALE Job started on Wed 13/02/2019 18:32:52
With Host name DESKTOP-J14NAA6
working directory C:\Users\Teddy\AppData\Local\Temp\scale.Teddy.9384
and process id 9384.
Input file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_69292.929293.inp
and output file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_69292.929293.out
##########################################################
***Warning:  The flux over a step has changed by more than 20%.
