SCALE Job started on Wed 13/02/2019 18:30:22
With Host name DESKTOP-J14NAA6
working directory C:\Users\Teddy\AppData\Local\Temp\scale.Teddy.8744
and process id 8744.
Input file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_43131.313131.inp
and output file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_43131.313131.out
##########################################################
***Warning:  The flux over a step has changed by more than 20%.
