SCALE Job started on Wed 13/02/2019 18:30:49
With Host name DESKTOP-J14NAA6
working directory C:\Users\Teddy\AppData\Local\Temp\scale.Teddy.13016
and process id 13016.
Input file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_47373.737374.inp
and output file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_47373.737374.out
##########################################################
***Warning:  The flux over a step has changed by more than 20%.
