SCALE Job started on Wed 13/02/2019 18:29:03
With Host name DESKTOP-J14NAA6
working directory C:\Users\Teddy\AppData\Local\Temp\scale.Teddy.12636
and process id 12636.
Input file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_28282.828283.inp
and output file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_28282.828283.out
##########################################################
