SCALE Job started on Wed 13/02/2019 18:30:10
With Host name DESKTOP-J14NAA6
working directory C:\Users\Teddy\AppData\Local\Temp\scale.Teddy.8480
and process id 8480.
Input file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_41010.101010.inp
and output file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_41010.101010.out
##########################################################
***Warning:  The flux over a step has changed by more than 20%.
