SCALE Job started on Wed 13/02/2019 18:28:31
With Host name DESKTOP-J14NAA6
working directory C:\Users\Teddy\AppData\Local\Temp\scale.Teddy.10896
and process id 10896.
Input file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_22626.262626.inp
and output file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_22626.262626.out
##########################################################
