SCALE Job started on Wed 13/02/2019 18:30:18
With Host name DESKTOP-J14NAA6
working directory C:\Users\Teddy\AppData\Local\Temp\scale.Teddy.6832
and process id 6832.
Input file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_42424.242424.inp
and output file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_42424.242424.out
##########################################################
***Warning:  The flux over a step has changed by more than 20%.
