SCALE Job started on Wed 13/02/2019 18:28:01
With Host name DESKTOP-J14NAA6
working directory C:\Users\Teddy\AppData\Local\Temp\scale.Teddy.10984
and process id 10984.
Input file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_15555.555556.inp
and output file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_15555.555556.out
##########################################################
