SCALE Job started on Wed 13/02/2019 18:31:16
With Host name DESKTOP-J14NAA6
working directory C:\Users\Teddy\AppData\Local\Temp\scale.Teddy.11452
and process id 11452.
Input file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_53030.303030.inp
and output file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_53030.303030.out
##########################################################
***Warning:  The flux over a step has changed by more than 20%.
