SCALE Job started on Wed 13/02/2019 18:27:55
With Host name DESKTOP-J14NAA6
working directory C:\Users\Teddy\AppData\Local\Temp\scale.Teddy.11128
and process id 11128.
Input file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_14141.414141.inp
and output file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_14141.414141.out
##########################################################
