SCALE Job started on Wed 13/02/2019 18:28:28
With Host name DESKTOP-J14NAA6
working directory C:\Users\Teddy\AppData\Local\Temp\scale.Teddy.12828
and process id 12828.
Input file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_21919.191919.inp
and output file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_21919.191919.out
##########################################################
