SCALE Job started on Wed 13/02/2019 18:32:48
With Host name DESKTOP-J14NAA6
working directory C:\Users\Teddy\AppData\Local\Temp\scale.Teddy.10912
and process id 10912.
Input file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_68585.858586.inp
and output file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_68585.858586.out
##########################################################
***Warning:  The flux over a step has changed by more than 20%.
