SCALE Job started on Wed 13/02/2019 18:32:41
With Host name DESKTOP-J14NAA6
working directory C:\Users\Teddy\AppData\Local\Temp\scale.Teddy.3608
and process id 3608.
Input file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_67171.717172.inp
and output file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_67171.717172.out
##########################################################
***Warning:  The flux over a step has changed by more than 20%.
