SCALE Job started on Wed 13/02/2019 18:31:01
With Host name DESKTOP-J14NAA6
working directory C:\Users\Teddy\AppData\Local\Temp\scale.Teddy.7008
and process id 7008.
Input file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_50202.020202.inp
and output file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_50202.020202.out
##########################################################
***Warning:  The flux over a step has changed by more than 20%.
