SCALE Job started on Wed 13/02/2019 18:29:51
With Host name DESKTOP-J14NAA6
working directory C:\Users\Teddy\AppData\Local\Temp\scale.Teddy.12672
and process id 12672.
Input file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_37474.747475.inp
and output file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_37474.747475.out
##########################################################
