SCALE Job started on Wed 13/02/2019 18:28:16
With Host name DESKTOP-J14NAA6
working directory C:\Users\Teddy\AppData\Local\Temp\scale.Teddy.11228
and process id 11228.
Input file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_19090.909091.inp
and output file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_19090.909091.out
##########################################################
