SCALE Job started on Wed 13/02/2019 18:32:57
With Host name DESKTOP-J14NAA6
working directory C:\Users\Teddy\AppData\Local\Temp\scale.Teddy.904
and process id 904.
Input file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_70000.000000.inp
and output file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_70000.000000.out
##########################################################
***Warning:  The flux over a step has changed by more than 20%.
