SCALE Job started on Wed 13/02/2019 18:32:07
With Host name DESKTOP-J14NAA6
working directory C:\Users\Teddy\AppData\Local\Temp\scale.Teddy.4964
and process id 4964.
Input file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_60808.080808.inp
and output file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_60808.080808.out
##########################################################
***Warning:  The flux over a step has changed by more than 20%.
