SCALE Job started on Wed 13/02/2019 18:32:00
With Host name DESKTOP-J14NAA6
working directory C:\Users\Teddy\AppData\Local\Temp\scale.Teddy.6240
and process id 6240.
Input file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_59393.939394.inp
and output file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_59393.939394.out
##########################################################
***Warning:  The flux over a step has changed by more than 20%.
