SCALE Job started on Wed 13/02/2019 18:31:56
With Host name DESKTOP-J14NAA6
working directory C:\Users\Teddy\AppData\Local\Temp\scale.Teddy.4496
and process id 4496.
Input file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_58686.868687.inp
and output file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_58686.868687.out
##########################################################
***Warning:  The flux over a step has changed by more than 20%.
