SCALE Job started on Wed 13/02/2019 18:30:26
With Host name DESKTOP-J14NAA6
working directory C:\Users\Teddy\AppData\Local\Temp\scale.Teddy.8480
and process id 8480.
Input file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_43838.383838.inp
and output file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_43838.383838.out
##########################################################
***Warning:  The flux over a step has changed by more than 20%.
