SCALE Job started on Wed 13/02/2019 18:31:25
With Host name DESKTOP-J14NAA6
working directory C:\Users\Teddy\AppData\Local\Temp\scale.Teddy.7900
and process id 7900.
Input file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_54444.444444.inp
and output file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_54444.444444.out
##########################################################
***Warning:  The flux over a step has changed by more than 20%.
