SCALE Job started on Wed 13/02/2019 18:31:47
With Host name DESKTOP-J14NAA6
working directory C:\Users\Teddy\AppData\Local\Temp\scale.Teddy.8864
and process id 8864.
Input file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_57272.727273.inp
and output file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_57272.727273.out
##########################################################
***Warning:  The flux over a step has changed by more than 20%.
