SCALE Job started on Wed 13/02/2019 18:31:04
With Host name DESKTOP-J14NAA6
working directory C:\Users\Teddy\AppData\Local\Temp\scale.Teddy.8764
and process id 8764.
Input file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_50909.090909.inp
and output file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_50909.090909.out
##########################################################
***Warning:  The flux over a step has changed by more than 20%.
