SCALE Job started on Wed 13/02/2019 18:29:54
With Host name DESKTOP-J14NAA6
working directory C:\Users\Teddy\AppData\Local\Temp\scale.Teddy.13184
and process id 13184.
Input file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_38181.818182.inp
and output file named C:\Users\Teddy\Desktop\scale_test\output\2.800000_38181.818182.out
##########################################################
